Shim from HTTP V1 library to coreHTTP [WinSim Only]
aws/amazon-freertos pull request #2739
Opened 2020-11-12 07:51 UTC by yourslab

Description
-----------

Provides backwards compatibility for the existing API by updating `IotHttpsClient_AddHeader` and `IotHttpsClient_InitializeRequest` to call their coreHTTP counterparts.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-12 18:35 UTC, yourslab commented
/bot run checks

2020-11-13 18:42 UTC, sarenameas commented on libraries/c_sdk/standard/https/src/iot_https_client.c
> +static IotHttpsReturnCode_t _shimConvertStatus( HTTPStatus_t coreHttpStatus )
Will you document this?

2020-11-14 08:05 UTC, sarenameas commented on libraries/c_sdk/standard/https/src/iot_https_client.c
> + * @param[in] coreHttpStatus - The status code from coreHTTP.
nitpick, @return

2020-11-16 19:56 UTC, sarenameas submitted a review, later dismissed

2020-11-16 23:47 UTC, gkwicker requested changes
One small grammar fix, see comments

2020-11-16 23:47 UTC, gkwicker commented on libraries/c_sdk/standard/https/src/iot_https_client.c
> + * @param[in] pJob - Pointer the to the HTTP request sending job.
grammar: _Pointer __to the__ HTTP..._

2020-11-17 00:00 UTC, yourslab commented on libraries/c_sdk/standard/https/src/iot_https_client.c
> + * @param[in] pJob - Pointer the to the HTTP request sending job.
Thanks for catching

2020-11-17 00:10 UTC, sarenameas approved these changes, later dismissed

2020-11-17 00:11 UTC, gkwicker submitted a review, later dismissed

2020-11-17 00:11 UTC, gkwicker approved these changes

2020-11-17 00:14 UTC, sarenameas approved these changes

2020-11-17 00:34 UTC, merged