Fix WiFi network deletion for ESP32
aws/amazon-freertos pull request #2909
Opened 2020-12-23 01:33 UTC by muneebahmed10

Description
-----------

In `libraries/c_sdk/standard/ble/src/services/wifi_provisioning/iot_ble_wifi_provisioning.c`, `_deleteNetworkTask` calls `_popNetwork` with a `NULL` network profile, so `WIFI_NetworkGet` is not called, and `ret` remains `eWiFiSuccess`. When `WIFI_NetworkDelete` is called, it is then possible for `usIndex < xRegistry.usNumNetworks` if no networks are saved, so `WIFI_NetworkDelete` returns success without deleting anything. `_popNetwork` will decrement `wifiProvisioning.numNetworks`, causing it to underflow to UINT_MAX. This fixes the issue by always returning `eWiFiFailure` when `usIndex >= xRegistry.usNumNetworks`.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-23 15:37 UTC, dachalco commented
/bot run checks

2020-12-23 16:32 UTC, dachalco requested changes

2020-12-23 16:32 UTC, dachalco commented on vendors/espressif/boards/esp32/ports/wifi/iot_wifi.c
> +			if( xRet == ESP_OK )
Perhaps, replacing[ entry to this _success_ block](https://github.com/aws/amazon-freertos/pull/2909/files#diff-b2e9f40dcf41678b337ff2ac1fa8ae4c06535ea4296c33fe419c319b4e90c245R1092)
```c
if( xRet == ESP_OK && usIndex < xRegistry.usNumNetworks )
```
with the following instead:
```c
if( xRet == ESP_OK && (0 < usIndex && usIndex < xRegistry.usNumNetworks ))
```
The latter spares runtime of block [1094, 1110] and may be more straightforward failure path when `usIndex == 0`

2020-12-23 16:56 UTC, dachalco approved these changes

2020-12-23 19:32 UTC, cobusve approved these changes

2020-12-23 21:12 UTC, muneebahmed10 commented
/bot run checks

2020-12-23 23:40 UTC, muneebahmed10 commented
/bot run checks

2020-12-24 00:52 UTC, ericyeh1995 commented
/bot run checks

2020-12-24 01:18 UTC, merged