Fix support for custom location of sdkconfig.defaults
aws/amazon-freertos pull request #3027
Opened 2021-03-04 09:18 UTC by amiotk

Description
-----------
Reported by myself in #3026 where specifying `IDF_SDKCONFIG_DEFAULTS` breaks CMake configure step.

Checklist:
----------
- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-04 10:14 UTC, shubhamkulkarni97 submitted a review, later dismissed

2021-03-11 18:43 UTC, yanjos-dev approved these changes

2021-03-11 18:43 UTC, yanjos-dev commented
/run bot checks

2021-03-11 18:45 UTC, yanjos-dev commented
/bot run checks

2021-03-11 21:42 UTC, yanjos-dev requested changes
Can you also include the patch mentioned in https://github.com/aws/amazon-freertos/issues/3026 in this change?

2021-03-11 23:16 UTC, yanjos-dev commented
/bot run checks

2021-03-12 04:35 UTC, shubhamkulkarni97 commented
Hi @yanjos-dev @amiotk,

I'm following up with the issue on freertos forum regarding the patch mentioned in #3026.
Please see https://forums.freertos.org/t/using-a-custom-sdkconfig-defaults-file/11908

We can merge this PR with patch in #3026 once above mentioned issue gets resolved.

Thanks,
Shubham

2021-03-23 04:49 UTC, shubhamkulkarni97 commented
@amiotk Can you apply patch provided in #3026 in this PR? It seems issue on freertos forum is fixed.

2021-03-31 05:56 UTC, shubhamkulkarni97 commented
Hi @yanjos-dev @lundinc2,
Can we get this PR merged?

2021-03-31 17:06 UTC, lundinc2 commented
@shubhamkulkarni97 I'll get this merged

2021-03-31 17:06 UTC, lundinc2 commented
/bot run checks

2021-03-31 17:27 UTC, lundinc2 approved these changes

2021-03-31 17:44 UTC, dan4thewin approved these changes

2021-03-31 18:10 UTC, yanjos-dev approved these changes

2021-03-31 18:11 UTC, merged