Malloc failed hook triggering fix
aws/amazon-freertos pull request #3177
Opened 2021-05-27 18:13 UTC by AniruddhaKanhere

Description
-----------
Malloc was being called with 0 size and thus a malloc failed hook was triggering. This PR fixes that.
Additionally, there was an issue when the device had written certificates to flash and it was just reset and restarted without re-flashing. The certificates were being cleaned by the library before it can re-write them and it got stuck in a loop since after cleaning, the library always added the "certificate present" flag and the size of the certificate (in this case, the size of the garbage data we want to over-write on the existing cert). And this flag was found by the code - and it tried to clean it again - forever stuck in a loop.
This PR fixes that too.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-05-27 22:40 UTC, paulbartell commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> + * @brief Delets a file from local storage by overwriting it.
Spelling

2021-05-27 22:41 UTC, paulbartell commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> + * @param[in] pcFileName    The name of the file to be written to.
s/written/deleted/?

2021-05-27 22:57 UTC, AniruddhaKanhere commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> + * @brief Delets a file from local storage by overwriting it.
Done.

2021-05-27 22:57 UTC, AniruddhaKanhere commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> + * @param[in] pcFileName    The name of the file to be written to.
Done, thanks!

2021-05-28 01:48 UTC, paulbartell requested changes

2021-05-28 01:48 UTC, paulbartell commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> +static BaseType_t prvFLASH_DeleteFile( char * pcFileName,
This function is never called.

2021-06-04 18:58 UTC, paulbartell commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> +    if (ulDataSize <= FMC_FLASH_PAGE_SIZE)
A loop would probably be a better choice here.

2021-06-04 20:00 UTC, paulbartell approved these changes

2021-06-07 05:51 UTC, cyliangtw reviewed
@AniruddhaKanhere , thanks of your modification. prvFLASH_delete purpose is to clean marker. The NVM page erase is enough to take over it, so gave some comments for below snippet.

2021-06-07 05:51 UTC, cyliangtw commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> +            pxZeroedData = pvPortMalloc( ulObjectLength );
To destroy object by prvFLASH_DeleteFile, it's not necessary to prepare pxZeroedData to zero out the object.

```suggestion

```

2021-06-07 05:51 UTC, cyliangtw commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> +                ( void ) memset( pxZeroedData, 0x0, ulObjectLength );
```suggestion
```

2021-06-07 05:51 UTC, cyliangtw commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> +                    if( prvFLASH_DeleteFile( pcFileName, pxZeroedData, ulObjectLength ) == pdFALSE )
```suggestion
                    if( prvFLASH_DeleteFile( pcFileName, ulObjectLength ) == pdFALSE )
```

2021-06-07 05:51 UTC, cyliangtw commented on vendors/nuvoton/boards/numaker_iot_m487_wifi/ports/pkcs11/core_pkcs11_pal.c
> +                vPortFree( pxZeroedData );
```suggestion
            
```

2021-06-07 17:55 UTC, merged

2021-06-07 18:04 UTC, AniruddhaKanhere commented
@cyliangtw, my github page wasn't refreshed and I pushed "merged" without seeing your comments. Apologies!
I'll create another PR to fix the issues that you pointed out.

2021-06-07 19:23 UTC, AniruddhaKanhere commented
@cyliangtw, please see PR https://github.com/aws/amazon-freertos/pull/3197.