Fixed compile-time warnings for ESP32 and ESP32-S2
aws/amazon-freertos pull request #3386
Opened 2021-09-14 06:24 UTC by laukik-hase

Description
-----------
Fixed the compile-time warnings which are observed when AFR is built for ESP32 and ESP32-S2. 

Checklist:
----------
- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-14 06:43 UTC, shubhamkulkarni97 requested changes
@laukik-hase I have left minor comments, overall LGTM

2021-09-14 06:43 UTC, shubhamkulkarni97 commented on vendors/espressif/boards/esp32/CMakeLists.txt
> +    ${AFR_ROOT_DIR}/vendors/espressif/boards/ports/wifi/iot_softap_wifi_provisioning.c
This file is under espressif port, can we actually remove unused function?

2021-09-14 06:43 UTC, shubhamkulkarni97 commented on vendors/espressif/boards/esp32/aws_demos/config_files/ota_demo_config.h
> +#undef MQTT_RECV_POLLING_TIMEOUT_MS
```suggestion
#ifndef MQTT_RECV_POLLING_TIMEOUT_MS
#define MQTT_RECV_POLLING_TIMEOUT_MS ( 1000U )
#endif
```

Consider this suggestion for all occurrences

2021-09-14 12:31 UTC, laukik-hase commented
This PR suppresses the compiler warnings in Amazon FreeRTOS library when building for ESP32. However, rather than suppressing those warnings at compile time, the code itself needs to be fixed at each site. 

As per #1629, is this issue being still tracked internally?

2021-09-23 16:52 UTC, shubhamkulkarni97 commented
@aggarg @mingyue86010 Could you take a look at this PR? It fixes build warnings for Espressif platforms

2021-09-23 18:22 UTC, aggarg approved these changes, later dismissed

2021-09-23 18:23 UTC, aggarg commented
/bot run checks

2021-09-24 05:15 UTC, laukik-hase commented
Updated style changes to fix CI failures

2021-09-27 05:43 UTC, aggarg commented
/bot run checks

2021-09-27 05:54 UTC, aggarg commented
/bot run checks

2021-09-27 06:25 UTC, aggarg approved these changes

2021-09-27 06:25 UTC, merged